version: "3.7"
networks:
  shield-network:

services:
  mysql:
    container_name: shield-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpw}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-shield}
      - MYSQL_USER=${MYSQL_USER:-shield-user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-shield-passwd}
    image: mysql:5.7.28
    networks:
      - shield-network
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  redis:
    container_name: shield-redis
    command: --appendonly yes --auto-aof-rewrite-min-size 16mb --stop-writes-on-bgsave-error no
    image: redis:5.0.6-alpine
    networks:
      - shield-network
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ./db/redis/data:/data
